[tools]
pipx = "latest"
"pipx:cruft" = "latest"

[tasks."template:update"]
description = "Update project with the latest changes from the template"
run = "cruft update"

[tasks."template:restore"]
description = "Restore template-managed files"
run = "cruft diff | git apply"
