[settings]
disable_backends = ["asdf"] # cannot be updated by Renovate

[tools]
node = "latest"
"npm:skills" = "latest"
pipx = "latest"
"pipx:cruft" = "latest"
worktrunk = "latest"

[tasks]
init = { run = ["git config core.hooksPath .githooks", "skills experimental_install", "cp -r .agents/. .claude"], description = "Initialise development environment" }
worktree-init = { run = "wt step copy-ignored --require-include", hide = true }
"template:update" = { run = "cruft update", description = "Update project with the latest changes from the template" }
"template:restore" = { run = "cruft diff | git apply", description = "Restore template-managed files" }
