[tools]
node = "latest"
"npm:skills" = "latest"
pipx = "latest"
"pipx:cruft" = "latest"
worktrunk = "latest"

[tasks.init]
description = "Initialise development environment"
run = [
  "git config core.hooksPath .githooks",
  "skills experimental_install",
  "cp -r .agents/. .claude",
  "echo @AGENTS.md > CLAUDE.md"
]

[tasks.worktree-init]
hide = true
run = "wt step copy-ignored --require-include"

[tasks."template:update"]
description = "Update project with the latest changes from the template"
run = "cruft update"

[tasks."template:restore"]
description = "Restore template-managed files"
run = "cruft diff | git apply"
