[settings]
disable_backends = ["asdf"] # cannot be updated by Renovate

[tools]
pipx = "latest"
"pipx:cruft" = "latest"

[tasks]
"template:update" = { run = "cruft update", description = "Update project with the latest changes from the template" }
"template:restore" = { run = "cruft diff | git apply", description = "Restore template-managed files" }
