name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c # v46.2.5
        with:
          renovate-version: 44.64.3@sha256:86141834dfebf540e0f545ac7f731c6fdc587592d5e95ae12ac5adc7ae22bca6
          token: ${{ secrets.RENOVATE_TOKEN || github.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: 'false'
          RENOVATE_ALLOWED_COMMANDS: '[".+"]'
